### ISSUE TITLE
Error: Definition for rule 'jsx-quotes' was not found.

### ISSUE THREAD

**Issue by cggaurav** [nebez/gulp-semistandard#3]
```
[13:38:27] Starting 'semistandard'...
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Definition for rule 'jsx-quotes' was not found.
    at /Users/cggaurav/Projects/apps/iteam/tsab/tsab_api/node_modules/gulp-semistandard/node_modules/semistandard/node_modules/standard-engine/node_modules/eslint/lib/eslint.js:646:27
    at Array.forEach (native)
    at EventEmitter.module.exports.api.verify (/Users/cggaurav/Projects/apps/iteam/tsab/tsab_api/node_modules/gulp-semistandard/node_modules/semistandard/node_modules/standard-engine/node_modules/eslint/lib/eslint.js:619:16)
    at processText (/Users/cggaurav/Projects/apps/iteam/tsab/tsab_api/node_modules/gulp-semistandard/node_modules/semistandard/node_modules/standard-engine/node_modules/eslint/lib/cli-engine.js:201:27)
    at CLIEngine.executeOnText (/Users/cggaurav/Projects/apps/iteam/tsab/tsab_api/node_modules/gulp-semistandard/node_modules/semistandard/node_modules/standard-engine/node_modules/eslint/lib/cli-engine.js:361:26)
    at Linter.lintText (/Users/cggaurav/Projects/apps/iteam/tsab/tsab_api/node_modules/gulp-semistandard/node_modules/semistandard/node_modules/standard-engine/index.js:63:54)
    at DestroyableTransform.processFile [as _transform] (/Users/cggaurav/Projects/apps/iteam/tsab/tsab_api/node_modules/gulp-semistandard/index.js:22:18)
    at DestroyableTransform.Transform._read (/Users/cggaurav/Projects/apps/iteam/tsab/tsab_api/node_modules/gulp-semistandard/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/Users/cggaurav/Projects/apps/iteam/tsab/tsab_api/node_modules/gulp-semistandard/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/Users/cggaurav/Projects/apps/iteam/tsab/tsab_api/node_modules/gulp-semistandard/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:1`
```

**Comment by tomusdrw** [comment]
Should be fixed in `0.2.1` (after bumping semistandard to 7.0.2)
